name: Homebrew Install Test

on:
  push:
    branches: [ trunk ]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  test-brew-install:
    strategy:
      matrix:
        os: [macos-15-intel, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:

      - name: Install Package from Homebrew
        run: |
          brew tap atsign-foundation/homebrew-tap
          brew install noports

      - name: Display Architecture and Version
        run: |
          echo "Currently running on:"
          uname -m
          
          echo "Binary path:"
          which noports
          
          echo "Package version info:"
          noports --version